### ISSUE TITLE
Can't get rv901 compiled ...

### ISSUE THREAD

**Issue by dlhenke** [Peter-van-Tol/LiteX-CNC#1]
Release 13.4 ngdbuild O.87xd (lin64)
Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

Command Line: /opt/Xilinx/13.4/ISE_DS/ISE/bin/lin64/unwrapped/ngdbuild -uc
rv901t.ucf rv901t.ngc rv901t.ngd

Reading NGO file "/home/durval/devel/LiteX-CNC/rv901t_emco5/gateware/rv901t.ngc"
...
Gathering constraint information from source properties...
Done.

Annotating constraints to design from ucf file "rv901t.ucf" ...
Resolving constraint associations...
Checking Constraint Associations...
ERROR:ConstraintSystem:59 - Constraint <NET "eth_tx_clk" TNM_NET =
   "PRDeth_tx_clk";> [rv901t.ucf(42)]: NET "eth_tx_clk" not found.  Please
   verify that:
   1. The specified design element actually exists in the original design.
   2. The specified object is spelled correctly in the constraint source file.

WARNING:ConstraintSystem:56 - Constraint <TIMESPEC "TSeth_tx_clk" = PERIOD
   "PRDeth_tx_clk" 8.0 ns HIGH 50%;> [rv901t.ucf(43)]: Unable to find an active
   'TNM' or 'TimeGrp' constraint named 'PRDeth_tx_clk'.

ERROR:ConstraintSystem:59 - Constraint <NET "eth_tx_clk" TNM_NET =
   "TIGeth_tx_clk";> [rv901t.ucf(54)]: NET "eth_tx_clk" not found.  Please
   verify that:
   1. The specified design element actually exists in the original design.
   2. The specified object is spelled correctly in the constraint source file.

WARNING:ConstraintSystem:56 - Constraint <TIMESPEC "TSsys_clkTOeth_tx_clk" =
   FROM "TIGsys_clk" TO "TIGeth_tx_clk" TIG;> [rv901t.ucf(55)]: Unable to find
   an active 'TimeGrp' or 'TNM' or 'TPSync' constraint named 'TIGeth_tx_clk'.

ERROR:ConstraintSystem:59 - Constraint <NET "eth_tx_clk" TNM_NET =
   "TIGeth_tx_clk";> [rv901t.ucf(66)]: NET "eth_tx_clk" not found.  Please
   verify that:
   1. The specified design element actually exists in the original design.
   2. The specified object is spelled correctly in the constraint source file.

WARNING:ConstraintSystem:56 - Constraint <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" =
   FROM "TIGeth_rx_clk" TO "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]: Unable to
   find an active 'TimeGrp' or 'TNM' or 'TPSync' constraint named
   'TIGeth_tx_clk'.

ERROR:ConstraintSystem:59 - Constraint <NET "eth_tx_clk" TNM_NET =
   "TIGeth_tx_clk";> [rv901t.ucf(71)]: NET "eth_tx_clk" not found.  Please
   verify that:
   1. The specified design element actually exists in the original design.
   2. The specified object is spelled correctly in the constraint source file.

WARNING:ConstraintSystem:56 - Constraint <TIMESPEC "TSeth_tx_clkTOsys_clk" =
   FROM "TIGeth_tx_clk" TO "TIGsys_clk" TIG;> [rv901t.ucf(73)]: Unable to find
   an active 'TimeGrp' or 'TNM' or 'TPSync' constraint named 'TIGeth_tx_clk'.

ERROR:ConstraintSystem:59 - Constraint <NET "eth_tx_clk" TNM_NET =
   "TIGeth_tx_clk";> [rv901t.ucf(77)]: NET "eth_tx_clk" not found.  Please
   verify that:
   1. The specified design element actually exists in the original design.
   2. The specified object is spelled correctly in the constraint source file.

WARNING:ConstraintSystem:56 - Constraint <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" =
   FROM "TIGeth_tx_clk" TO "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]: Unable to
   find an active 'TimeGrp' or 'TNM' or 'TPSync' constraint named
   'TIGeth_tx_clk'.

INFO:ConstraintSystem:178 - TNM 'PRDclk25', used in period specification
   'TSclk25', was traced into PLL_ADV instance PLL_ADV. The following new TNM
   groups and period specifications were generated at the PLL_ADV output(s): 
   CLKOUT0: <TIMESPEC TS_crg_clkout = PERIOD "crg_clkout" TSclk25 / 2 HIGH 50%>

WARNING:ConstraintSystem:191 - The TNM 'PRDeth_tx_clk', does not directly or
   indirectly drive any flip-flops, latches and/or RAMS and cannot be actively
   used by the referencing Period constraint 'TSeth_tx_clk'. If clock manager
   blocks are directly or indirectly driven, a new TNM constraint will not be
   derived even though the referencing constraint is a PERIOD constraint unless
   an output of the clock manager drives flip-flops, latches or RAMs. This TNM
   is used in the following user PERIOD specification:
   <TIMESPEC "TSeth_tx_clk" = PERIOD "PRDeth_tx_clk" 8.0 ns HIGH 50%;>
   [rv901t.ucf(43)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clk" = PERIOD "PRDeth_tx_clk" 8.0 ns HIGH 50%;>
   [rv901t.ucf(43)]

WARNING:ConstraintSystem:192 - The TNM 'TIGeth_tx_clk', does not directly or
   indirectly drive any flip-flops, latches and/or RAMS and cannot be actively
   used by the referencing TIg constraint ''. If clock manager blocks are
   directly or indirectly driven, a new TNM constraint will not be derived since
   the none of the referencing constraints are a PERIOD constraint. This TNM is
   used in the following user groups and/or specifications:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:192 - The TNM 'TIGeth_tx_clk', does not directly or
   indirectly drive any flip-flops, latches and/or RAMS and cannot be actively
   used by the referencing TIg constraint ''. If clock manager blocks are
   directly or indirectly driven, a new TNM constraint will not be derived since
   the none of the referencing constraints are a PERIOD constraint. This TNM is
   used in the following user groups and/or specifications:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:192 - The TNM 'TIGeth_tx_clk', does not directly or
   indirectly drive any flip-flops, latches and/or RAMS and cannot be actively
   used by the referencing TIg constraint ''. If clock manager blocks are
   directly or indirectly driven, a new TNM constraint will not be derived since
   the none of the referencing constraints are a PERIOD constraint. This TNM is
   used in the following user groups and/or specifications:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:192 - The TNM 'TIGeth_tx_clk', does not directly or
   indirectly drive any flip-flops, latches and/or RAMS and cannot be actively
   used by the referencing TIg constraint ''. If clock manager blocks are
   directly or indirectly driven, a new TNM constraint will not be derived since
   the none of the referencing constraints are a PERIOD constraint. This TNM is
   used in the following user groups and/or specifications:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSsys_clkTOeth_tx_clk" = FROM "TIGsys_clk" TO "TIGeth_tx_clk"
   TIG;> [rv901t.ucf(55)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_rx_clkTOeth_tx_clk" = FROM "TIGeth_rx_clk" TO
   "TIGeth_tx_clk" TIG;> [rv901t.ucf(67)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOsys_clk" = FROM "TIGeth_tx_clk" TO "TIGsys_clk"
   TIG;> [rv901t.ucf(73)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSeth_tx_clkTOeth_rx_clk" = FROM "TIGeth_tx_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(79)]

WARNING:NgdBuild:1345 - The constraint <TIMESPEC "TSeth_rx_clk" = PERIOD
   "PRDeth_rx_clk" 8.0 ns HIGH 50%;> [rv901t.ucf(38)] is overridden by the
   constraint <TIMESPEC "TSeth_rx_clk" = PERIOD "PRDeth_rx_clk" 8.0 ns HIGH
   50%;> [rv901t.ucf(84)]. The overriden constraint usually comes from the input
   netlist or ncf files. Please set XIL_NGDBUILD_CONSTR_OVERRIDE_ERROR to
   promote this message to an error.
WARNING:NgdBuild:1345 - The constraint <TIMESPEC "TSsys_clkTOeth_rx_clk" = FROM
   "TIGsys_clk" TO "TIGeth_rx_clk" TIG;> [rv901t.ucf(49)] is overridden by the
   constraint <TIMESPEC "TSsys_clkTOeth_rx_clk" = FROM "TIGsys_clk" TO
   "TIGeth_rx_clk" TIG;> [rv901t.ucf(90)]. The overriden constraint usually
   comes from the input netlist or ncf files. Please set
   XIL_NGDBUILD_CONSTR_OVERRIDE_ERROR to promote this message to an error.
WARNING:NgdBuild:1345 - The constraint <TIMESPEC "TSeth_rx_clkTOsys_clk" = FROM
   "TIGeth_rx_clk" TO "TIGsys_clk" TIG;> [rv901t.ucf(61)] is overridden by the
   constraint <TIMESPEC "TSeth_rx_clkTOsys_clk" = FROM "TIGeth_rx_clk" TO
   "TIGsys_clk" TIG;> [rv901t.ucf(96)]. The overriden constraint usually comes
   from the input netlist or ncf files. Please set
   XIL_NGDBUILD_CONSTR_OVERRIDE_ERROR to promote this message to an error.
Done...

Checking expanded design ...

Partition Implementation Status
-------------------------------

  No Partitions were found in this design.

-------------------------------

NGDBUILD Design Results Summary:
  Number of errors:     5
  Number of warnings:  30

Total memory usage is 439320 kilobytes

Total REAL time to NGDBUILD completion:  4 sec
Total CPU time to NGDBUILD completion:   4 sec

One or more errors were found during NGDBUILD.  No NGD file will be written.

Writing NGDBUILD log file "rv901t.bld"...

**Comment by Peter-van-Tol** [comment]
This is due to an issue with Litex, please refer to https://github.com/enjoy-digital/litex/issues/1502
